#!/usr/bin/env python3
"""Director-field memory driven by explicit nested-contact energy.

The angular potential is generated by unilateral circumferential contact, not
inserted as a Gaussian or first-harmonic ansatz.  A full annulus is the null;
a polar core under a one-sided pad is the candidate architecture.
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from scipy.interpolate import CubicSpline
from scipy.linalg import eigh_tridiagonal
from scipy.optimize import minimize


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "DATA" / "contact_derived_director_memory.json"
FIG = ROOT / "FIGURES" / "contact_derived_director_memory.svg"


def contact_table(window: str, polar_offset: float, npsi: int = 2048, nphi: int = 4096):
    phi = np.linspace(-np.pi, np.pi, nphi, endpoint=False)
    psi = np.linspace(0.0, 2.0 * np.pi, npsi + 1)
    dphi = 2.0 * np.pi / nphi
    d, u, v = 0.22, 0.14, 0.18
    ff = phi[None, :]
    pp = psi[:, None]
    compression = np.maximum(
        d + u * np.cos(2.0 * ff) - v * np.cos(2.0 * (ff - pp))
        + polar_offset * np.cos(ff - pp),
        0.0,
    )
    if window == "annulus":
        weight = np.ones_like(phi)
    elif window == "one_sided":
        weight = (np.cos(phi) >= 0.0).astype(float)
    else:
        raise ValueError(window)
    energy = 0.5 * np.sum(weight[None, :] * compression**2, axis=1) * dphi
    energy[-1] = energy[0]
    energy -= np.min(energy)
    spline = CubicSpline(psi, energy, bc_type="periodic")
    return psi, energy, spline


def contact_window(s: np.ndarray, left: float = 0.38, right: float = 0.62, edge: float = 0.018):
    return 0.25 * (1.0 + np.tanh((s - left) / edge)) * (1.0 - np.tanh((s - right) / edge))


def bubble_seed(s: np.ndarray, left: float = 0.34, right: float = 0.66, width: float = 0.035):
    return 0.5 * np.pi * (np.tanh((s - left) / width) - np.tanh((s - right) / width))


class DirectorProblem:
    def __init__(self, n: int, spline: CubicSpline, contact_scale: float, c_twist=0.010, k_bulk=0.050):
        self.n = n
        self.s = np.linspace(0.0, 1.0, n)
        self.ds = self.s[1] - self.s[0]
        self.g = contact_window(self.s)
        self.spline = spline
        self.contact_scale = contact_scale
        self.c_twist = c_twist
        self.k_bulk = k_bulk

    def full(self, y):
        return np.concatenate(([0.0], y, [0.0]))

    def energy_grad(self, y):
        p = self.full(y)
        dp = np.diff(p)
        e_twist = 0.5 * self.c_twist / self.ds * np.sum(dp * dp)
        v_bulk = 0.5 * self.k_bulk * np.sin(p) ** 2
        v_contact = self.contact_scale * self.g * self.spline(np.mod(p, 2.0 * np.pi))
        weights = np.ones(self.n)
        weights[[0, -1]] = 0.5
        energy = e_twist + self.ds * np.sum(weights * (v_bulk + v_contact))

        grad = self.c_twist / self.ds * (2.0 * p[1:-1] - p[:-2] - p[2:])
        grad += self.ds * (
            0.5 * self.k_bulk * np.sin(2.0 * p[1:-1])
            + self.contact_scale * self.g[1:-1] * self.spline(np.mod(p[1:-1], 2.0 * np.pi), 1)
        )
        return float(energy), grad

    def hessian_min(self, y):
        p = self.full(y)
        diag = 2.0 * self.c_twist / self.ds + self.ds * (
            self.k_bulk * np.cos(2.0 * p[1:-1])
            + self.contact_scale * self.g[1:-1] * self.spline(np.mod(p[1:-1], 2.0 * np.pi), 2)
        )
        off = np.full(self.n - 3, -self.c_twist / self.ds)
        return float(eigh_tridiagonal(diag, off, select="i", select_range=(0, 0))[0][0])

    def solve(self, seed):
        result = minimize(
            lambda y: self.energy_grad(y),
            np.asarray(seed)[1:-1],
            method="L-BFGS-B",
            jac=True,
            options={"ftol": 1e-13, "gtol": 2e-9, "maxiter": 6000, "maxls": 60},
        )
        p = self.full(result.x)
        e, grad = self.energy_grad(result.x)
        return {
            "profile": p,
            "energy": e,
            "grad_inf": float(np.max(np.abs(grad))),
            "hessian_min": self.hessian_min(result.x),
            "peak_over_pi": float(np.max(p) / np.pi),
            "variation_over_pi": float(np.sum(np.abs(np.diff(p))) / np.pi),
            "contact_mean_cos": float(np.sum(self.g * np.cos(p)) / np.sum(self.g)),
            "success": bool(result.success),
            "message": result.message,
        }


def compact(solution):
    return {k: v for k, v in solution.items() if k != "profile"}


def scan_branch(spline, n, scales):
    s = np.linspace(0.0, 1.0, n)
    seed = bubble_seed(s)
    records = []
    for scale in scales:
        problem = DirectorProblem(n, spline, float(scale))
        sol = problem.solve(seed)
        zero = problem.solve(np.zeros(n))
        seed = sol["profile"]
        records.append({
            "scale": float(scale),
            **compact(sol),
            "zero_energy": float(zero["energy"]),
            "domain_excess_energy": float(sol["energy"] - zero["energy"]),
        })
    return records


def first_zero_crossing(records):
    """Interpolate a bubble/zero energy crossing along a descending branch."""
    for a, b in zip(records[:-1], records[1:]):
        ya, yb = a["domain_excess_energy"], b["domain_excess_energy"]
        if ya == 0.0:
            return float(a["scale"])
        if ya * yb < 0.0:
            return float(a["scale"] + (b["scale"] - a["scale"]) * (-ya) / (yb - ya))
    return None


def main():
    psi, u_annulus, spl_annulus = contact_table("annulus", polar_offset=0.10)
    _, u_polar, spl_polar = contact_table("one_sided", polar_offset=0.10)

    c_twist, k_bulk = 0.010, 0.050
    wall_pair_cost = 4.0 * np.sqrt(c_twist * k_bulk)
    effective_width = float(np.trapezoid(contact_window(np.linspace(0, 1, 10001)), np.linspace(0, 1, 10001)))
    delta_contact = float(spl_polar(0.0) - spl_polar(np.pi))
    energetic_threshold_estimate = wall_pair_cost / (effective_width * delta_contact)

    scale_test = 7.0
    grids = [61, 81, 101, 141, 181]
    grid_results = {}
    profiles = {}
    for n in grids:
        s = np.linspace(0.0, 1.0, n)
        seed = bubble_seed(s)
        row = {}
        for name, spline in (("annulus", spl_annulus), ("polar_one_sided", spl_polar)):
            problem = DirectorProblem(n, spline, scale_test, c_twist, k_bulk)
            zero = problem.solve(np.zeros(n))
            bubble = problem.solve(seed)
            row[name] = {"zero_seed": compact(zero), "bubble_seed": compact(bubble)}
            if n == 141:
                profiles[name] = {"s": s, "zero": zero["profile"], "bubble": bubble["profile"]}
        grid_results[str(n)] = row

    # Follow the candidate bubble branch downward from strong contact.  The
    # annular branch is scanned identically as a null.
    scales_down = np.linspace(16.0, 0.0, 129)
    branch_polar = scan_branch(spl_polar, 141, scales_down)
    branch_annulus = scan_branch(spl_annulus, 141, scales_down)

    # Locate the lowest scale at which a nontrivial positive-Hessian state is retained.
    retained_polar = [r for r in branch_polar if r["peak_over_pi"] > 0.75 and r["hessian_min"] > 0.0]
    retained_annulus = [r for r in branch_annulus if r["peak_over_pi"] > 0.75 and r["hessian_min"] > 0.0]
    numerical_retention_threshold = float(min(r["scale"] for r in retained_polar)) if retained_polar else None
    annulus_retention_threshold = float(min(r["scale"] for r in retained_annulus)) if retained_annulus else None
    numerical_global_crossing = first_zero_crossing(branch_polar)

    payload = {
        "status": "GEN/CANDIDATE; synthetic mechanics test, not H(s)H evidence",
        "field_energy": "integral [C/2 psi_s^2 + K_A/2 sin^2 psi + Lambda g(s) U_contact(psi)] ds",
        "contact_parameters": {"preload": 0.22, "sleeve_quad": 0.14, "core_quad": 0.18, "polar_offset": 0.10},
        "field_parameters": {"C_twist": c_twist, "K_bulk": k_bulk, "test_contact_scale": scale_test},
        "analytic_estimates": {
            "single_wall_energy": float(2.0 * np.sqrt(c_twist * k_bulk)),
            "wall_pair_cost": float(wall_pair_cost),
            "effective_contact_width": effective_width,
            "U0_minus_Upi_one_sided": delta_contact,
            "global_energy_crossing_estimate": float(energetic_threshold_estimate),
        },
        "numerical_retention_thresholds": {
            "polar_one_sided": numerical_retention_threshold,
            "annulus": annulus_retention_threshold,
        },
        "numerical_global_crossings": {
            "polar_one_sided": numerical_global_crossing,
            "annulus": first_zero_crossing(branch_annulus),
        },
        "grid_refinement": grid_results,
        "branch_polar_one_sided": branch_polar,
        "branch_annulus": branch_annulus,
    }
    DATA.parent.mkdir(parents=True, exist_ok=True)
    FIG.parent.mkdir(parents=True, exist_ok=True)
    DATA.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    fig, axes = plt.subplots(2, 3, figsize=(14.2, 7.7), constrained_layout=True)
    x = psi / np.pi
    axes[0, 0].plot(x, u_annulus, lw=2.1, label="polar core + annulus", color="#2c7fb8")
    axes[0, 0].plot(x, u_polar, lw=2.1, label="polar core + one-sided pad", color="#d95f0e")
    axes[0, 0].set(title="Contact-derived angular potentials", xlabel=r"$\psi/\pi$", ylabel=r"$U_c-U_{c,\min}$")
    axes[0, 0].legend(frameon=False)

    for name, color in (("annulus", "#2c7fb8"), ("polar_one_sided", "#d95f0e")):
        pr = profiles[name]
        axes[0, 1].plot(pr["s"], pr["bubble"] / np.pi, lw=2.2, color=color, label=name.replace("_", " "))
    axes[0, 1].plot(profiles["annulus"]["s"], contact_window(profiles["annulus"]["s"]), "k--", lw=1.3, label="contact window")
    axes[0, 1].set(title=rf"Bubble-seeded equilibria, $\Lambda={scale_test:g}$", xlabel="normalized arclength s", ylabel=r"$\psi/\pi$")
    axes[0, 1].legend(frameon=False)

    for records, color, label in ((branch_annulus, "#2c7fb8", "annulus"), (branch_polar, "#d95f0e", "one-sided polar")):
        scale = np.array([r["scale"] for r in records])
        peak = np.array([r["peak_over_pi"] for r in records])
        axes[1, 0].plot(scale, peak, "o-", ms=3.0, lw=1.7, color=color, label=label)
    axes[1, 0].axvline(energetic_threshold_estimate, color="0.35", ls="--", lw=1.2, label="wall-cost estimate")
    axes[1, 0].set(title="Continuation from a strong-contact domain", xlabel=r"contact scale $\Lambda$", ylabel=r"peak $\psi/\pi$")
    axes[1, 0].legend(frameon=False)

    for records, color, label in ((branch_annulus, "#2c7fb8", "annulus"), (branch_polar, "#d95f0e", "one-sided polar")):
        scale = np.array([r["scale"] for r in records])
        hmin = np.array([r["hessian_min"] for r in records])
        axes[1, 1].plot(scale, hmin, "o-", ms=3.0, lw=1.7, color=color, label=label)
    axes[1, 1].axhline(0.0, color="k", lw=1.0)
    axes[1, 1].set(title="Local-stability gate", xlabel=r"contact scale $\Lambda$", ylabel="minimum discrete Hessian eigenvalue")
    axes[1, 1].legend(frameon=False)

    for records, color, label in ((branch_annulus, "#2c7fb8", "annulus"), (branch_polar, "#d95f0e", "one-sided polar")):
        scale = np.array([r["scale"] for r in records])
        excess = np.array([r["domain_excess_energy"] for r in records])
        axes[0, 2].plot(scale, excess, "o-", ms=3.0, lw=1.7, color=color, label=label)
    axes[0, 2].axhline(0.0, color="k", lw=1.0)
    axes[0, 2].axvline(energetic_threshold_estimate, color="0.35", ls="--", lw=1.2, label="wall-only estimate")
    if numerical_global_crossing is not None:
        axes[0, 2].axvline(numerical_global_crossing, color="#d95f0e", ls=":", lw=1.5, label="numerical crossing")
    axes[0, 2].set(title="Domain versus zero-state energy", xlabel=r"contact scale $\Lambda$", ylabel=r"$E_{domain}-E_0$")
    axes[0, 2].legend(frameon=False)

    ns = np.array(grids, dtype=float)
    for name, color, label in (("annulus", "#2c7fb8", "annulus"), ("polar_one_sided", "#d95f0e", "one-sided polar")):
        excess = np.array([
            grid_results[str(n)][name]["bubble_seed"]["energy"]
            - grid_results[str(n)][name]["zero_seed"]["energy"] for n in grids
        ])
        axes[1, 2].plot(1.0 / ns, excess, "o-", lw=1.7, color=color, label=label)
    axes[1, 2].set(title=rf"Grid refinement at $\Lambda={scale_test:g}$", xlabel=r"grid spacing proxy $1/N$", ylabel=r"$E_{domain}-E_0$")
    axes[1, 2].legend(frameon=False)
    for ax in axes.flat:
        ax.grid(alpha=0.22)
    fig.suptitle("Contact-derived director memory: polar pad versus annular null", fontsize=14)
    fig.savefig(FIG, format="svg")

    summary = {
        "estimate": energetic_threshold_estimate,
        "retention_thresholds": {
            "polar_one_sided": numerical_retention_threshold,
            "annulus": annulus_retention_threshold,
        },
        "global_crossing": numerical_global_crossing,
        "N181": grid_results["181"],
    }
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
