#!/usr/bin/env python3
"""Blind inverse/discriminator test for anisotropic pre-twist coherence.

Synthetic poles are generated by a two-component finite-element carrier with
rotating constitutive axes.  The inverse model only sees noisy pole pairs.
It estimates the isotropic ladder coefficient, total twist density, and
anisotropy; then predicts a withheld magic-coherence length.  A generous
length-independent normalized-splitting null is fitted for comparison.
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import eigh
from scipy.optimize import least_squares


plt.rcParams["svg.fonttype"] = "none"
OUT_JSON = Path("pretwist_inverse_discriminator.json")
OUT_SVG = Path("pretwist_inverse_discriminator.svg")
OUT_PNG = Path("pretwist_inverse_discriminator.png")


def coherence(n: int, x: np.ndarray | float) -> np.ndarray:
    """Absolute first-order coherence factor, with removable singular limits."""
    x = np.asarray(x, dtype=float)
    out = np.empty_like(x)
    z = np.isclose(x, 0.0, atol=1e-10)
    r = np.isclose(x, n * np.pi, atol=1e-8)
    reg = ~(z | r)
    out[z] = 1.0
    out[r] = 0.5
    out[reg] = np.abs(
        n**2 * np.pi**2 * np.sin(x[reg])
        / (x[reg] * (n**2 * np.pi**2 - x[reg] ** 2))
    )
    return out


def assemble(length: float, c_iso: float, epsilon: float, delta: float,
             elements: int) -> tuple[np.ndarray, np.ndarray]:
    """Linear FE matrices for -d_s[C(s)d_s] with natural/free endpoints."""
    nodes = elements + 1
    h = length / elements
    size = 2 * nodes
    stiffness = np.zeros((size, size))
    mass = np.zeros((size, size))
    scalar_k = np.array([[1.0, -1.0], [-1.0, 1.0]]) / h
    scalar_m = h * np.array([[2.0, 1.0], [1.0, 2.0]]) / 6.0
    body = c_iso * np.diag([1.0 + epsilon, 1.0 - epsilon])
    for e in range(elements):
        angle = delta * (e + 0.5) * h
        rot = np.array([[np.cos(angle), -np.sin(angle)],
                        [np.sin(angle), np.cos(angle)]])
        constitutive = rot @ body @ rot.T
        for a in range(2):
            ia = slice(2 * (e + a), 2 * (e + a) + 2)
            for b in range(2):
                ib = slice(2 * (e + b), 2 * (e + b) + 2)
                stiffness[ia, ib] += scalar_k[a, b] * constitutive
                mass[ia, ib] += scalar_m[a, b] * np.eye(2)
    return stiffness, mass


def pole_pairs(length: float, c_iso: float, epsilon: float, delta: float,
               elements: int, modes: int = 2) -> list[tuple[float, float]]:
    k, m = assemble(length, c_iso, epsilon, delta, elements)
    vals = eigh(k, m, eigvals_only=True, subset_by_index=[0, 2 * modes + 3])
    positive = vals[vals > 1e-8]
    return [(float(positive[2*i]), float(positive[2*i+1]))
            for i in range(modes)]


def fit_inverse(rows: list[dict]) -> dict:
    q2 = np.array([r["q2"] for r in rows])
    means = np.array([r["mean"] for r in rows])
    c_hat = float(np.dot(q2, means) / np.dot(q2, q2))
    splits = np.array([r["split"] for r in rows])
    lengths = np.array([r["length"] for r in rows])
    modes = np.array([r["mode"] for r in rows], dtype=int)

    def residual(theta: np.ndarray) -> np.ndarray:
        delta, epsilon = theta
        pred = np.array([
            2*c_hat*q_e*epsilon*coherence(int(n), delta*l)
            for q_e, n, l in zip(q2, modes, lengths)
        ], dtype=float)
        return pred - splits

    fits = []
    for d0 in np.linspace(0.35, 5.5, 24):
        sol = least_squares(residual, [d0, 0.015], bounds=([0.05, 0.0], [7.0, 0.08]))
        fits.append(sol)
    best = min(fits, key=lambda s: float(np.dot(s.fun, s.fun)))
    delta_hat, epsilon_hat = map(float, best.x)
    rss = float(np.dot(best.fun, best.fun))

    basis = 2*c_hat*q2
    null_amp = float(np.dot(basis, splits) / np.dot(basis, basis))
    null_resid = basis*null_amp - splits
    null_rss = float(np.dot(null_resid, null_resid))
    count = len(rows)
    aic_coh = count*np.log(rss/count) + 2*2
    aic_null = count*np.log(null_rss/count) + 2*1
    return {
        "c_iso_hat": c_hat,
        "delta_hat": delta_hat,
        "epsilon_hat": epsilon_hat,
        "rss_coherence": rss,
        "null_normalized_amplitude": null_amp,
        "rss_constant_null": null_rss,
        "aic_coherence": float(aic_coh),
        "aic_constant_null": float(aic_null),
        "delta_aic_null_minus_coherence": float(aic_null-aic_coh),
    }


def main() -> None:
    rng = np.random.default_rng(260107)
    truth = {"c_iso": 0.06, "epsilon": 0.018, "delta": 2.2}
    elements = 120
    train_lengths = [0.72, 0.96, 1.23, 1.55, 1.91, 2.25]
    noise_fraction = 2.0e-4
    rows = []
    for length in train_lengths:
        for mode, (lo, hi) in enumerate(pole_pairs(length, **truth, elements=elements), 1):
            noisy = np.sort(np.array([lo, hi]) * (1 + rng.normal(0, noise_fraction, 2)))
            q2 = (mode*np.pi/length)**2
            rows.append({"length": length, "mode": mode, "q2": q2,
                         "low": float(noisy[0]), "high": float(noisy[1]),
                         "mean": float(noisy.mean()), "split": float(noisy[1]-noisy[0])})

    fit = fit_inverse(rows)
    magic_length = 2*np.pi/truth["delta"]
    hold_lo, hold_hi = pole_pairs(magic_length, **truth, elements=elements, modes=1)[0]
    hold_split = hold_hi-hold_lo
    q2_hold = (np.pi/magic_length)**2
    pred_coh = float(2*fit["c_iso_hat"]*q2_hold*fit["epsilon_hat"]
                     * coherence(1, fit["delta_hat"]*magic_length))
    pred_null = float(2*fit["c_iso_hat"]*q2_hold*fit["null_normalized_amplitude"])
    baseline_hold = truth["c_iso"]*q2_hold

    # Profile objective makes aliases visible rather than hiding them in one optimizer return.
    dgrid = np.linspace(0.1, 7.0, 900)
    q2 = np.array([r["q2"] for r in rows])
    s = np.array([r["split"] for r in rows])
    lengths = np.array([r["length"] for r in rows])
    modes = np.array([r["mode"] for r in rows])
    profile = []
    eps_profile = []
    for d in dgrid:
        b = np.array([2*fit["c_iso_hat"]*q*coherence(int(n), d*l)
                      for q, n, l in zip(q2, modes, lengths)])
        e = max(0.0, float(np.dot(b, s)/np.dot(b, b)))
        profile.append(float(np.sum((e*b-s)**2)))
        eps_profile.append(e)
    profile = np.array(profile)
    local_idx = np.where((profile[1:-1] < profile[:-2]) &
                         (profile[1:-1] < profile[2:]))[0] + 1
    ranked_idx = local_idx[np.argsort(profile[local_idx])][:5]
    alias_minima = [
        {"delta": float(dgrid[i]), "epsilon": float(eps_profile[i]),
         "rss_ratio_to_best": float(profile[i]/profile.min())}
        for i in ranked_idx
    ]

    result = {
        "status": "GEN/CANDIDATE",
        "truth_used_only_by_generator": truth,
        "finite_elements": elements,
        "relative_pole_noise_sigma": noise_fraction,
        "training_lengths": train_lengths,
        "training_modes": [1, 2],
        "fit": fit,
        "profile_alias_minima": alias_minima,
        "withheld_magic_test": {
            "length": float(magic_length),
            "condition": "delta_true*L=2*pi for n=1",
            "fem_split": float(hold_split),
            "coherence_prediction": pred_coh,
            "constant_null_prediction": pred_null,
            "fem_split_over_isotropic_lambda": float(hold_split/baseline_hold),
            "coherence_abs_error": float(abs(pred_coh-hold_split)),
            "null_abs_error": float(abs(pred_null-hold_split)),
            "null_to_coherence_abs_error_ratio": float(
                abs(pred_null-hold_split)/abs(pred_coh-hold_split)
            ),
        },
        "identifiability": {
            "mean_ladder_identifies": "c_iso (and any additive baseline if included)",
            "splitting_after_ladder_identifies": "epsilon and delta, subject to finite-length alias minima",
            "splitting_without_mean_ladder_identifies_only": "product c_iso*epsilon plus delta",
        },
        "strict_detector_null": "a readout tensor can change modal weights but not generalized-eigenvalue pole locations",
        "generous_null": "length-independent normalized splitting, representing extrinsic boundary or fitting bias",
        "failure_gate": "reject discriminator if profile minima are not isolated or withheld magic suppression is absent above FE/noise remainder",
    }
    OUT_JSON.write_text(json.dumps(result, indent=2)+"\n", encoding="utf-8")

    fig, axes = plt.subplots(1, 3, figsize=(13.2, 4.1))
    for n, marker in [(1, "o"), (2, "s")]:
        rr = [r for r in rows if r["mode"] == n]
        x = np.array([r["length"] for r in rr])
        y = np.array([r["split"]/(2*fit["c_iso_hat"]*r["q2"]) for r in rr])
        axes[0].plot(x, y, marker, label=f"FE poles, n={n}")
        xx = np.linspace(min(train_lengths), magic_length, 400)
        axes[0].plot(xx, fit["epsilon_hat"]*coherence(n, fit["delta_hat"]*xx), lw=1.5)
    axes[0].axvline(magic_length, ls="--", color="0.35", label="withheld n=1 zero")
    axes[0].set(xlabel="segment length L", ylabel="normalized pole split",
                title="Length/mode coherence fingerprint")
    axes[0].legend(fontsize=7)
    axes[0].grid(alpha=.25)

    axes[1].semilogy(dgrid, profile/profile.min(), color="#7b3f98")
    axes[1].axvline(truth["delta"], color="black", ls="--", label="hidden truth")
    axes[1].axvline(fit["delta_hat"], color="#d95f02", ls=":", label="inverse fit")
    axes[1].set(xlabel=r"twist density $\delta$", ylabel="profile RSS / minimum",
                title="Alias audit")
    axes[1].legend(fontsize=7)
    axes[1].grid(alpha=.25)

    labels = ["FE withheld", "coherence", "constant null"]
    vals = [hold_split, pred_coh, pred_null]
    axes[2].bar(labels, vals, color=["black", "#1b9e77", "#d95f02"])
    axes[2].set_yscale("log")
    axes[2].tick_params(axis="x", rotation=18)
    axes[2].set(ylabel="n=1 pole splitting", title="Withheld magic-length test")
    axes[2].grid(alpha=.25, axis="y")
    fig.tight_layout()
    fig.savefig(OUT_SVG)
    fig.savefig(OUT_PNG, dpi=170)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
